#!/bin/bash

killall cfprefsd

while read shortname
do
    uid=$(id -u "$shortname")

    if [ -n "$uid" ]
    then
        /bin/launchctl asuser "$uid" /bin/launchctl unload /Library/LaunchAgents/com.github.ygini.hello-it.plist
        /bin/launchctl asuser "$uid" /bin/launchctl remove com.github.ygini.hello-it
        /bin/launchctl asuser "$uid" /bin/launchctl load /Library/LaunchAgents/com.github.ygini.hello-it.plist
    fi
done < <(ps aux | grep "MacOS/[F]inder" | awk '{print $1}')

exit 0
